apiVersion: argoproj.io/v1alpha1
kind: AppSource
metadata:
  name: guestbook # Application name
  namespace: qa-payments-us-west-2 #Includes project name
spec:
  path: kustomize-guestbook
  repoURL: https://github.com/argoproj/argocd-example-apps
  