kind: Kustomization

namespace: argocd

resources:
- deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1

images:
- name: controller
  newName: quay.io/argoprojlabs/argocd-appsource
  newTag: latest
