# permissions for end users to edit appsources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appsource-editor-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - appsources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - appsources/status
  verbs:
  - get
