apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-appsource-cm
  namespace: argocd
data:
  #Use localhost:8080 ArgoCD was installed locally
  argocd.address: 172.17.0.6:8080 # Argo CD server hostname and port
  project.pattern: '(?P<project>.*)-us-(west|east)-(\d.*)'
