apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-appsource-cm
  namespace: argocd
data:
  argocd.address: 172.17.0.6:8080
  argocd.clientOpts: "--insecure"
  project.profiles: |
    - my-project:
        namePattern: (?P<project>.*)-us-(west|east)-(\d.*)
        spec:
          description: US West/East projects
          sourceRepos:
          - 'https://github.com/argoproj/*'
    - default:
        namePattern: .*
        spec:
          description: Default AppSource project
          sourceRepos:
            - '*'