apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-appsource-cm
  namespace: argocd
data:
  argocd.address: localhost:8080 # Argo CD server hostname and port
  # Argo CD access token
  project.pattern: '(?P<project>.*)-us-(west|east)-(\d.*)'