apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-appsource-controller
  labels:
    app.kubernetes.io/name: argocd-appsource-controller
    app.kubernetes.io/part-of: argocd-appsource
    app.kubernetes.io/component: controller
